
USUARIOS_WS = "USUARIOS"

ID_LABEL = "ID"
UNAVAILABLE = "No Disponible"
FECHA_REGISTRO_LABEL = "FECHA REGISTRO"
CATEGORIA_LABEL = "CATEGORIA"
EQUIPO_LABEL = "EQUIPO"
JUGADOR_LABEL = "JUGADOR"
CHECKIN_LABEL = "CHECK-IN"

FECHA_NACIMIENTO_LABEL = "FECHA DE NACIMIENTO"
EDAD_LABEL = "EDAD"

MENSAJE_NO_DATA = "El Jugador seleccionado no cuenta con datos suficientes para mostrar esta sección"

EQUIPO_PROMEDIO = "A"

COLUMNAS_USADAS = [ID_LABEL, JUGADOR_LABEL, CATEGORIA_LABEL, EQUIPO_LABEL]

COLUMNAS_COMUNES_JCE = [JUGADOR_LABEL, CATEGORIA_LABEL, EQUIPO_LABEL]
COLUMNAS_COMUNES = [FECHA_REGISTRO_LABEL, ID_LABEL, CATEGORIA_LABEL, EQUIPO_LABEL]
COLUMNAS_EXCLUIDAS_PROMEDIO = COLUMNAS_COMUNES

COLUMNAS_EXCLUIDAS_DROP = ["anio", "mes"]
COLUMNAS_EXCLUIDAS = [FECHA_REGISTRO_LABEL, ID_LABEL, JUGADOR_LABEL, CATEGORIA_LABEL, EQUIPO_LABEL, "anio", "mes", "TEST"]

COLUMNAS = [FECHA_REGISTRO_LABEL, ID_LABEL, JUGADOR_LABEL, CATEGORIA_LABEL, EQUIPO_LABEL]

